# Generated by Django 5.2.16 on 2026-07-31 00:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=220)),
                ('type', models.CharField(choices=[('documentaire', 'Documentaire'), ('podcast', 'Podcast')], default='documentaire', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('lien', models.URLField(blank=True, max_length=600, verbose_name='Lien (video/audio)')),
                ('duree', models.CharField(blank=True, max_length=30, verbose_name='Duree')),
                ('publie', models.BooleanField(default=True)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
                'ordering': ['-date_publication'],
            },
        ),
    ]
