# Generated by Django 5.0.14 on 2026-09-18 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=240)),
                ('type', models.CharField(choices=[('documentaire', 'Documentaire'), ('enquete', 'Enquête'), ('reportage', 'Reportage'), ('document', 'Document'), ('rapport', 'Rapport'), ('video', 'Vidéo'), ('audio', 'Audio'), ('photo', 'Photo / Album'), ('autre', 'Autre')], default='document', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bibliotheque/images/', verbose_name='Vignette')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='bibliotheque/fichiers/', verbose_name='Fichier (PDF, vidéo, audio, document...)')),
                ('lien', models.URLField(blank=True, max_length=600, verbose_name='Lien externe')),
                ('video_url', models.URLField(blank=True, max_length=600, verbose_name='Vidéo YouTube')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Document de la bibliothèque',
                'verbose_name_plural': 'Bibliothèque (productions Xamsa)',
                'ordering': ['-date'],
            },
        ),
    ]
