# Generated by Django 5.2.16 on 2026-08-04 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCommunaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('lien', models.URLField(blank=True, max_length=600)),
                ('meta', models.CharField(blank=True, max_length=140, verbose_name='Info complémentaire')),
                ('publie', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('contribution', 'Espace contribution'), ('concours', 'Concours'), ('association', 'Association de presse'), ('opportunite', 'Opportunité')], default='contribution', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaSenegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('lien', models.URLField(blank=True, max_length=600)),
                ('meta', models.CharField(blank=True, max_length=140, verbose_name='Info complémentaire')),
                ('publie', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('histoire', 'Histoire des médias'), ('portrait', 'Portrait de journaliste'), ('tv', 'Chaîne TV'), ('radio', 'Radio'), ('presse', 'Presse écrite'), ('numerique', 'Média numérique'), ('podcast', 'Podcast')], default='histoire', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('lien', models.URLField(blank=True, max_length=600)),
                ('meta', models.CharField(blank=True, max_length=140, verbose_name='Info complémentaire')),
                ('publie', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('cours', 'Cours'), ('formation', 'Formation'), ('webinaire', 'Webinaire'), ('ressource', 'Ressource'), ('certification', 'Certification')], default='cours', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
