# Generated by Django 5.0.14 on 2026-08-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcommunaute',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo (fichier)'),
        ),
        migrations.AddField(
            model_name='mediasenegal',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo (fichier)'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo (fichier)'),
        ),
    ]
