# Generated by Django 5.2.16 on 2026-07-31 00:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('type', models.CharField(choices=[('enquete', 'Enquete'), ('reportage', 'Reportage'), ('dossier', 'Dossier'), ('analyse', 'Analyse')], default='enquete', max_length=20)),
                ('chapo', models.TextField(blank=True, verbose_name='Chapo (accroche)')),
                ('corps', models.TextField(blank=True, verbose_name="Corps de l'article")),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Image (fichier)')),
                ('image_url', models.URLField(blank=True, max_length=600, verbose_name='Image (URL externe)')),
                ('temps_lecture', models.PositiveIntegerField(default=6, verbose_name='Temps de lecture (min)')),
                ('a_la_une', models.BooleanField(default=False, verbose_name='A la une')),
                ('publie', models.BooleanField(default=True, verbose_name='Publie')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='redaction.categorie')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
