# Generated by Django 5.0.14 on 2026-08-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, help_text="Lien YouTube : la vidéo sera affichée dans l'article.", max_length=600, verbose_name='Vidéo YouTube (URL)'),
        ),
    ]
