# Generated by Django 5.0.14 on 2026-09-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redaction', '0002_article_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='derniere_minute',
            field=models.BooleanField(default=False, help_text="Affiche cette publication dans le carrousel « Dernière minute » de l'accueil.", verbose_name='Dernière minute (carrousel accueil)'),
        ),
    ]
