# Generated by Django 5.2.16 on 2026-07-31 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('url_rss', models.URLField(max_length=500, verbose_name='Flux RSS')),
                ('site', models.URLField(blank=True, max_length=300, verbose_name='Site web')),
                ('categorie', models.CharField(default='Presse', max_length=60)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RevueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=400)),
                ('resume', models.TextField(blank=True, verbose_name='Resume / analyse')),
                ('url', models.URLField(max_length=600, verbose_name='Lien vers la source')),
                ('image_url', models.URLField(blank=True, max_length=600, verbose_name='Image (URL)')),
                ('date', models.DateTimeField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='veille.source')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('source', 'url'), name='revueitem_unique_source_url')],
            },
        ),
    ]
