# Generated by Django 5.2.16 on 2026-08-04 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_profil', models.CharField(choices=[('lecteur', 'Lecteur / Citoyen'), ('journaliste', 'Journaliste / Contributeur'), ('etudiant', "Étudiant de l'Académie"), ('organe', 'Organe de presse / Association')], default='lecteur', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('localisation', models.CharField(blank=True, max_length=120)),
                ('organisation', models.CharField(blank=True, max_length=160)),
                ('bio', models.TextField(blank=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
