# Generated by Django 5.2.16 on 2026-08-05 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sujet', 'Proposition de sujet'), ('article', 'Article'), ('rapport', 'Rapport / dossier'), ('tribune', 'Tribune / analyse'), ('audio', 'Audio'), ('video', 'Vidéo')], default='sujet', max_length=20)),
                ('titre', models.CharField(max_length=240)),
                ('categorie', models.CharField(blank=True, max_length=60)),
                ('resume', models.TextField(blank=True, verbose_name='Résumé')),
                ('corps', models.TextField(blank=True, verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contributions/images/', verbose_name='Image de la publication')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='contributions/fichiers/', verbose_name='Fichier (audio, vidéo, document)')),
                ('statut', models.CharField(choices=[('attente', 'En attente de validation'), ('publie', 'Publié'), ('refuse', 'Refusé')], default='attente', max_length=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
