# Generated by Django 5.0.14 on 2026-08-14 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_commentaire_reaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('commentaire', 'Commentaire'), ('reponse', 'Réponse'), ('jaime', "J'aime")], max_length=12)),
                ('lu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_emises', to=settings.AUTH_USER_MODEL)),
                ('commentaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.commentaire')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='comptes.contribution')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
