# Generated by Django 5.0.14 on 2026-08-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_contribution_vues_favori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='moderation_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contribution',
            name='moderation_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contribution',
            name='moderation_verdict',
            field=models.CharField(blank=True, choices=[('', 'Non évalué'), ('publier', 'Recommandé'), ('reviser', 'À vérifier'), ('rejeter', 'À rejeter')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profil',
            name='de_confiance',
            field=models.BooleanField(default=False, help_text='Ses contributions jugées bonnes sont publiées automatiquement.', verbose_name='Contributeur de confiance'),
        ),
    ]
