# Generated by Django 5.0.14 on 2026-08-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_contribution_moderation_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='destination',
            field=models.CharField(blank=True, choices=[('', 'Espace contribution (par défaut)'), ('enquete', 'Enquêtes'), ('reportage', 'Reportages'), ('dossier', 'Dossiers'), ('politique', 'Actualité · Politique'), ('cours', 'Académie · Cours'), ('formation', 'Académie · Formation'), ('concours', 'Communauté · Concours'), ('opportunite', 'Communauté · Opportunité'), ('association', 'Communauté · Association de presse'), ('histoire', 'Médias du Sénégal · Histoire des médias'), ('portrait', 'Médias du Sénégal · Portrait de journaliste')], default='', max_length=20, verbose_name='Destination (rubrique)'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube : la vidéo sera affichée dans la publication.', max_length=600, verbose_name='Vidéo YouTube (URL)'),
        ),
    ]
